sonar.host.url=https://sonarcloud.io
sonar.organization=congregacionmt
sonar.projectKey=jonimeichtry11
sonar.projectName=Jonathan Meichtry

sonar.sources=src
sonar.exclusions=**/*.spec.ts, src/environments/**, src/assets/**, e2e/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=**/*.spec.ts
